steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - .
  - '--tag=gcr.io/marine-service-397521/image3' # Adjust image name and project ID
images:
- 'gcr.io/marine-service-397521/image3' # Adjust image name and project ID
